const missions = [
// Grand Tournament 2021
// BRB Matched @line 202
  {
    id: 1,
    book: "Grand Tournament 2021",
    label: "Crossfire",
    type: "Incursion",
    roll: 11,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Outflank",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Crossfire",
  },
  {
    id: 2,
    book: "Grand Tournament 2021",
    label: "Resupply",
    type: "Incursion",
    roll: 12,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Secure Landing Sites",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Resupply",
  },
  {
    id: 3,
    book: "Grand Tournament 2021",
    label: "Raid",
    type: "Incursion",
    roll: 13,
    primaryObjective: "Domination",
    primaryIncrement: 5,
    specialSecondary: "Raid Supply Lines",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Raid",
  },
  {
    id: 4,
    book: "Grand Tournament 2021",
    label: "Center Ground",
    type: "Incursion",
    roll: 21,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Centre Ground",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Raid",
  },
  {
    id: 5,
    book: "Grand Tournament 2021",
    label: "Ascension",
    type: "Incursion",
    roll: 22,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Ascend",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Ascension",
  },
  {
    id: 6,
    book: "Grand Tournament 2021",
    label: "Forward Push",
    type: "Incursion",
    roll: 23,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Forward Push",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Forward-Push",
  },
  {
    id: 7,
    book: "Grand Tournament 2021",
    label: "Rise of the Machine Spirit",
    type: "Incursion",
    roll: 31,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Inload Data-Psalm",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Rise-of-the-Machine-Spirit",
  },
  {
    id: 8,
    book: "Grand Tournament 2021",
    label: "Show of Force",
    type: "Incursion",
    roll: 32,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Minimise Losses",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Show-of-Force",
  },
  {
    id: 9,
    book: "Grand Tournament 2021",
    label: "Reconnaissance Mission",
    type: "Incursion",
    roll: 33,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Recon Sweep",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Reconnaissance-Mission",
  },
  {
    id: 10,
    book: "Grand Tournament 2021",
    label: "Retrieval Mission",
    type: "Strike Force",
    roll: 11,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Minimise Losses",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Retrieval-Mission",
  },
  {
    id: 11,
    book: "Grand Tournament 2021",
    label: "Scorched Earth",
    type: "Strike Force",
    roll: 12,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Raze",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Scorched-Earth",
  },
  {
    id: 12,
    book: "Grand Tournament 2021",
    label: "Vital Intelligence",
    type: "Strike Force",
    roll: 13,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Inload Data-Psalm",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Vital-Intelligence",
  },
  {
    id: 13,
    book: "Grand Tournament 2021",
    label: "Surround and Destroy",
    type: "Strike Force",
    roll: 21,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Surrond Them",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Surround-and-Destroy",
  },
  {
    id: 14,
    book: "Grand Tournament 2021",
    label: "Battle Lines",
    type: "Strike Force",
    roll: 22,
    primaryObjective: "Domination",
    primaryIncrement: 5,
    specialSecondary: "Vital Ground",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Battle-Lines",
  },
  {
    id: 15,
    book: "Grand Tournament 2021",
    label: "The Scouring",
    type: "Strike Force",
    roll: 23,
    primaryObjective: "Domination",
    primaryIncrement: 5,
    specialSecondary: "Strategic Scan",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#The-Scouring",
  },
  {
    id: 16,
    book: "Grand Tournament 2021",
    label: "Overrun",
    type: "Strike Force",
    roll: 31,
    primaryObjective: "Domination",
    primaryIncrement: 5,
    specialSecondary: "Overrun",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Overrun",
  },
  {
    id: 17,
    book: "Grand Tournament 2021",
    label: "Sweep and Clear",
    type: "Strike Force",
    roll: 32,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Direct Assault",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Sweep-and-Clear",
  },
  {
    id: 18,
    book: "Grand Tournament 2021",
    label: "Priority Target",
    type: "Strike Force",
    roll: 33,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Priority Targets",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Priority-Target",
  },
  // Big Rule Book
  {
    id: 19,
    book: "Big Rule Book: Matched Play",
    label: "Incisive Attack",
    type: "Combat Patrol",
    roll: 1,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Surgical Assault",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Incisive-Attack",
  },
  {
    id: 20,
    book: "Big Rule Book: Matched Play",
    label: "Outriders",
    type: "Combat Patrol",
    roll: 2,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Survey",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Outriders",
  },
  {
    id: 21,
    book: "Big Rule Book: Matched Play",
    label: "Encircle",
    type: "Combat Patrol",
    roll: 3,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Enicircle",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Encircle",
  },
  {
    id: 22,
    book: "Big Rule Book: Matched Play",
    label: "Divide and Conquer",
    type: "Incursion",
    roll: 1,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Lines of Demarcation",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Divide-and-Conquer",
  },
  {
    id: 23,
    book: "Big Rule Book: Matched Play",
    label: "Crossfire",
    type: "Incursion",
    roll: 2,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Outflank",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Crossfire",
  },
  {
    id: 24,
    book: "Big Rule Book: Matched Play",
    label: "Centre-Ground",
    type: "Incursion",
    roll: 3,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Centre Ground",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Centre-Ground",
  },
  {
    id: 25,
    book: "Big Rule Book: Matched Play",
    label: "Forward Push",
    type: "Incursion",
    roll: 4,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Forward Push",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Forward-Push",
  },
  {
    id: 26,
    book: "Big Rule Book: Matched Play",
    label: "Ransack",
    type: "Incursion",
    roll: 5,
    primaryObjective: "Domination",
    primaryIncrement: 5,
    specialSecondary: "Ransack",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Ransack",
  },
  {
    id: 27,
    book: "Big Rule Book: Matched Play",
    label: "Shifting Front",
    type: "Incursion",
    roll: 6,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Test Their Line",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Shifting-Front",
  },
  {
    id: 28,
    book: "Big Rule Book: Matched Play",
    label: "Retrieval Mission",
    type: "Strike Force",
    roll: 1,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Minimise Losses",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Retrieval-Mission",
  },
  {
    id: 29,
    book: "Big Rule Book: Matched Play",
    label: "Front-Line Warfare",
    type: "Strike Force",
    roll: 2,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Vital Ground",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Front-Line-Warfare",
  },
  {
    id: 28,
    book: "Big Rule Book: Matched Play",
    label: "The Four Pillars",
    type: "Strike Force",
    roll: 3,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Siphon Power",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#The-Four-Pillars",
  },
  {
    id: 29,
    book: "Big Rule Book: Matched Play",
    label: "No Mans Land",
    type: "Strike Force",
    roll: 4,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Secure No Man's Land",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#No-Mans-Land",
  },
  {
    id: 30,
    book: "Big Rule Book: Matched Play",
    label: "Scorched-Earth",
    type: "Strike Force",
    roll: 5,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Raze",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Scorched-Earth",
  },
  {
    id: 31,
    book: "Big Rule Book: Matched Play",
    label: "Vital Intelligence",
    type: "Strike Force",
    roll: 6,
    primaryObjective: "Domination",
    primaryIncrement: 5,
    specialSecondary: "Data Intercept",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Vital-Intelligence",
  },
  {
    id: 32,
    book: "Big Rule Book: Matched Play",
    label: "Lines of Battle",
    type: "Onslaught",
    roll: 1,
    primaryObjective: "Unified Advance",
    primaryIncrement: 5,
    specialSecondary: "Hold the Center",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Lines-of-Battle",
  },
  {
    id: 33,
    book: "Big Rule Book: Matched Play",
    label: "All-OutWar",
    type: "Onslaught",
    roll: 2,
    primaryObjective: "Domination",
    primaryIncrement: 5,
    specialSecondary: "Surround Them",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#All-Out-War",
  },
  {
    id: 34,
    book: "Big Rule Book: Matched Play",
    label: "Pathway to Glory",
    type: "Onslaught",
    roll: 3,
    primaryObjective: "Domination",
    primaryIncrement: 5,
    specialSecondary: "Search for the Portal",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/matched-play/#Pathway-to-Glory",
  },
  

];

export default missions;
