const missions = [
  {
    id: 1,
    book: "Grand Tournament 2021",
    label: "Crossfire",
    type: "Incursion",
    roll: 11,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Outflank",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Crossfire",
  },
  {
    id: 2,
    book: "Grand Tournament 2021",
    label: "Resupply",
    type: "Incursion",
    roll: 12,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Secure Landing Sites",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Resupply",
  },
  {
    id: 3,
    book: "Grand Tournament 2021",
    label: "Raid",
    type: "Incursion",
    roll: 13,
    primaryObjective: "Domination",
    primaryIncrement: 5,
    specialSecondary: "Raid Supply Lines",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Raid",
  },
  {
    id: 4,
    book: "Grand Tournament 2021",
    label: "Center Ground",
    type: "Incursion",
    roll: 21,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Centre Ground",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Raid",
  },
  {
    id: 5,
    book: "Grand Tournament 2021",
    label: "Ascension",
    type: "Incursion",
    roll: 22,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Ascend",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Ascension",
  },
  {
    id: 6,
    book: "Grand Tournament 2021",
    label: "Forward Push",
    type: "Incursion",
    roll: 23,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Forward Push",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Forward-Push",
  },
  {
    id: 7,
    book: "Grand Tournament 2021",
    label: "Rise of the Machine Spirit",
    type: "Incursion",
    roll: 31,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Inload Data-Psalm",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Rise-of-the-Machine-Spirit",
  },
  {
    id: 8,
    book: "Grand Tournament 2021",
    label: "Show of Force",
    type: "Incursion",
    roll: 32,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Minimise Losses",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Show-of-Force",
  },
  {
    id: 9,
    book: "Grand Tournament 2021",
    label: "Reconnaissance Mission",
    type: "Incursion",
    roll: 33,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Recon Sweep",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Reconnaissance-Mission",
  },
  {
    id: 1,
    book: "Grand Tournament 2021",
    label: "Retrieval Mission",
    type: "Strike Force",
    roll: 11,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Minimise Losses",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Retrieval-Mission",
  },
  {
    id: 1,
    book: "Grand Tournament 2021",
    label: "Scorched Earth",
    type: "Strike Force",
    roll: 12,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Raze",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Scorched-Earth",
  },
  {
    id: 1,
    book: "Grand Tournament 2021",
    label: "Vital Intelligence",
    type: "Strike Force",
    roll: 13,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Inload Data-Psalm",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Vital-Intelligence",
  },
  {
    id: 1,
    book: "Grand Tournament 2021",
    label: "Surround and Destroy",
    type: "Strike Force",
    roll: 21,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Surrond Them",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Surround-and-Destroy",
  },
  {
    id: 1,
    book: "Grand Tournament 2021",
    label: "Battle Lines",
    type: "Strike Force",
    roll: 22,
    primaryObjective: "Domination",
    primaryIncrement: 5,
    specialSecondary: "Vital Ground",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Battle-Lines",
  },
  {
    id: 1,
    book: "Grand Tournament 2021",
    label: "The Scouring",
    type: "Strike Force",
    roll: 23,
    primaryObjective: "Domination",
    primaryIncrement: 5,
    specialSecondary: "Strategic Scan",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#The-Scouring",
  },
  {
    id: 1,
    book: "Grand Tournament 2021",
    label: "Overrun",
    type: "Strike Force",
    roll: 31,
    primaryObjective: "Domination",
    primaryIncrement: 5,
    specialSecondary: "Overrun",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Overrun",
  },
  {
    id: 1,
    book: "Grand Tournament 2021",
    label: "Sweep and Clear",
    type: "Strike Force",
    roll: 32,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Direct Assault",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Sweep-and-Clear",
  },
  {
    id: 1,
    book: "Grand Tournament 2021",
    label: "Priority Target",
    type: "Strike Force",
    roll: 33,
    primaryObjective: "Take and Hold",
    primaryIncrement: 5,
    specialSecondary: "Priority Targets",
    url: "https://wahapedia.ru/wh40k9ed/the-rules/grand-tournament-2021/#Priority-Target",
  },
];

export default missions;
